version: '3.8'
services:
    app:
        image: fallebr/kuis
        container_name: web-server
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/php-mysqli:/var/www/html/ 
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
        MYSQL_DATABASE: akademik
        ports:
            - "9906:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '3060:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
